export ALTERNATE_EDITOR=""
export BROWSER="chrome"
export EDITOR="$HOME/.bin/em"
export EMAIL="wintonmr@gmail.com"
export HISTFILESIZE=20000
export HOMEBREW_NO_ANALYTICS=1
export LANG="en_NZ"
export LC_ALL="en_NZ.UTF-8"
export LC_CTYPE="en_NZ.UTF-8"
export NAME="Michael Winton"
export PROMPT_DIRTRIM=3
export TERM=xterm-256color
